Repository GDGoCINHA/24-2_GDGoC_Server, pull requests merged in 2025-08, with the labels that each got.

#202 [REFACTOR] #197: 기존 신입 멤버 가입 신청 및 조회 api 리팩토링
  src/main/java/inha/gdgoc/domain/auth/exception/AuthErrorCode.java
  src/main/java/inha/gdgoc/domain/auth/exception/AuthException.java
  src/main/java/inha/gdgoc/domain/auth/service/AuthService.java
  src/main/java/inha/gdgoc/domain/recruit/controller/RecruitMemberController.java
  src/main/java/inha/gdgoc/domain/recruit/dto/request/CheckStudentIdRequest.java
  src/main/java/inha/gdgoc/domain/recruit/dto/request/RecruitMemberRequest.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/AnswerResponse.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/AnswersResponse.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/CheckPhoneNumberResponse.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/CheckStudentIdResponse.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/SpecifiedMemberResponse.java
  src/main/java/inha/gdgoc/domain/recruit/exception/RecruitMemberErrorCode.java
  src/main/java/inha/gdgoc/domain/recruit/exception/RecruitMemberException.java
  src/main/java/inha/gdgoc/domain/recruit/repository/AnswerRepository.java
  src/main/java/inha/gdgoc/domain/recruit/service/RecruitMemberService.java
  src/main/java/inha/gdgoc/domain/resource/exception/ResourceErrorCode.java
  src/main/java/inha/gdgoc/domain/resource/exception/ResourceException.java
  src/main/java/inha/gdgoc/domain/study/exception/StudyAttendeeErrorCode.java
  src/main/java/inha/gdgoc/domain/study/exception/StudyAttendeeException.java
  src/main/java/inha/gdgoc/domain/study/exception/StudyErrorCode.java
  src/main/java/inha/gdgoc/domain/study/exception/StudyException.java
  src/main/java/inha/gdgoc/domain/user/exception/UserErrorCode.java
  src/main/java/inha/gdgoc/domain/user/exception/UserException.java
  src/main/java/inha/gdgoc/global/config/jwt/TokenProvider.java
  src/main/java/inha/gdgoc/global/config/openapi/OpenApiConfig.java
  src/main/java/inha/gdgoc/global/dto/response/ApiResponse.java
  src/main/java/inha/gdgoc/global/dto/response/ErrorResponse.java
  src/main/java/inha/gdgoc/global/exception/BusinessException.java
  src/main/java/inha/gdgoc/global/exception/ErrorCode.java
  src/main/java/inha/gdgoc/global/exception/GlobalErrorCode.java
  src/main/java/inha/gdgoc/global/exception/GlobalExceptionHandler.java
  src/main/java/inha/gdgoc/global/security/SecurityConfig.java
Labels: refactor

#204 [FEAT] #197: 신규 멤버 모집 관련 관리자 페이지 api 구현
  src/main/java/inha/gdgoc/domain/recruit/controller/RecruitMemberController.java
  src/main/java/inha/gdgoc/domain/recruit/controller/message/RecruitMemberMessage.java
  src/main/java/inha/gdgoc/domain/recruit/dto/request/PaymentUpdateRequest.java
  src/main/java/inha/gdgoc/domain/recruit/dto/request/RecruitMemberRequest.java
  src/main/java/inha/gdgoc/domain/recruit/dto/response/RecruitMemberSummaryResponse.java
  src/main/java/inha/gdgoc/domain/recruit/entity/RecruitMember.java
  src/main/java/inha/gdgoc/domain/recruit/enums/AdmissionSemester.java
  src/main/java/inha/gdgoc/domain/recruit/repository/RecruitMemberRepository.java
  src/main/java/inha/gdgoc/domain/recruit/service/RecruitMemberService.java
  src/main/java/inha/gdgoc/global/dto/response/PageMeta.java
  src/main/java/inha/gdgoc/global/util/SemesterCalculator.java
  src/main/resources/db/migration/V20250826__admission_semester_add_backfill_enforce.sql
Labels: enhancement, refactor

#208 [HOTFIX] CORS 해결
  src/main/java/inha/gdgoc/global/security/SecurityConfig.java
  src/main/java/inha/gdgoc/global/security/TokenAuthenticationFilter.java
Labels: bug

#210 [FIX] #209: 중복 email 검증 오류 해결
  src/main/java/inha/gdgoc/domain/user/controller/UserController.java
Labels: bug

#215 [FIX] #213 : logout 404 에러 수정
  src/main/java/inha/gdgoc/global/security/TokenAuthenticationFilter.java
Labels: bug
